server:
  port: 8091
spring:
  jpa:
    properties:
       hibernate:
          dialect:org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
      
  datasource:
        name: test
        username: root
        password: root
        url: jdbc:mysql://localhost:3306/microservices
        driver-class-name: com.mysql.jdbc.Driver
  
        
